//! Export the image back to `world/*.mst` text for source control
//! (`docs/IMAGE.md` §6) — a **surgical, in-place** update, not a from-scratch
//! regeneration.
//!
//! Why surgical: classes are *reopened* across many files (e.g. `28_point.mst`
//! reopens `Object`/`Number`/`Integer`), and the image merges every reopening
//! into one record with no file-provenance column. The FILES are therefore the
//! only record of "which method lives where", so we edit each method where it
//! already sits — replacing only the bodies that actually changed — and route
//! anything with no home (a class or method created in the GUI) to one
//! exporter-owned additions file. Consequences:
//!   - unchanged methods are byte-identical, so `git diff` shows exactly the
//!     interactive edits and nothing else;
//!   - re-exporting an unchanged image touches no file (idempotent);
//!   - the emitted `.mst` re-imports to the same image (round-trips).
//!
//! v1 scope: method-body edits + brand-new classes/methods. Not yet: exporting a
//! method DELETED in the image (left in its file), or a class-definition/ivar
//! edit (only method bodies are spliced). Those are follow-ups; the GUI outliner
//! — the main editing surface — only does method edits + add-class/add-method,
//! which this covers fully.

use crate::{mst, Image};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

/// The one file the exporter fully owns and regenerates: everything in the image
/// that has no home in a hand-authored `world/*.mst` lands here.
pub const ADDITIONS_FILE: &str = "50_image_additions.mst";

const ADDITIONS_HEADER: &str = "\"50_image_additions.mst — AUTO-GENERATED by the GUI's \
'Save World to Files' (image_store::export). Classes and methods created in the \
image (e.g. via the class browser) that don't yet live in a hand-authored world \
file are collected here so they can be reviewed and checked in. Move a definition \
into a topic file by hand and it will stay there on the next export.\"\n";

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct ExportStats {
    pub files_changed: usize,
    pub methods_updated: usize,
    pub methods_added: usize,
    pub methods_removed: usize,
    pub classes_added: usize,
}

/// Remove a method's block from a file's text: the parsed `source` plus the
/// indentation before it and the newline after, so no ragged blank line is left.
fn remove_block(text: &str, source: &str) -> Option<String> {
    let pos = text.find(source)?;
    let bytes = text.as_bytes();
    let mut start = pos;
    while start > 0 && matches!(bytes[start - 1], b' ' | b'\t') {
        start -= 1;
    }
    let mut end = pos + source.len();
    if text[end..].starts_with('\n') {
        end += 1;
    }
    let mut out = String::with_capacity(text.len());
    out.push_str(&text[..start]);
    out.push_str(&text[end..]);
    Some(out)
}

/// A `Super subclass: Name [ … ]` block for the additions file or a home-file
/// reopening. `with_header` includes the class's ivars/classVars (a brand-new
/// class needs them; a reopening that only adds methods doesn't).
pub(crate) fn class_block(
    superclass: &str,
    name: &str,
    instance_vars: &str,
    class_vars: &str,
    method_sources: &[String],
    with_header: bool,
) -> String {
    let mut s = format!("{superclass} subclass: {name} [\n");
    if with_header {
        if !instance_vars.trim().is_empty() {
            s.push_str(&format!("    | {} |\n", instance_vars.trim()));
        }
        if !class_vars.trim().is_empty() {
            s.push_str(&format!("    <classVars: {}>\n", class_vars.trim()));
        }
    }
    for src in method_sources {
        // Indent to the class-body level with 4 spaces on the FIRST line only —
        // the method body keeps its own internal indentation, matching the
        // hand-authored files AND the parser's captured source, so a re-parse
        // equals the stored source and re-export stays idempotent (no churn).
        s.push_str("    ");
        s.push_str(src.trim_end());
        s.push('\n');
    }
    s.push_str("]\n");
    s
}

/// The `.mst` filenames named in `world.list`, in load order (comments and blank
/// lines skipped — same format `import_world_dir` reads). `world.list`, not a
/// directory glob, is the canonical world: a stray `.mst` isn't part of it.
fn read_world_list(world_dir: &Path) -> Result<Vec<String>, String> {
    let list_path = world_dir.join("world.list");
    let text = fs::read_to_string(&list_path)
        .map_err(|e| format!("reading {}: {e}", list_path.display()))?;
    Ok(parse_list(&text))
}

fn parse_list(text: &str) -> Vec<String> {
    text.lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| l.to_string())
        .collect()
}

/// Every `.mst` named by ANY `*.list` in `world_dir` — the full set of
/// hand-authored files, not just `world.list`'s.
///
/// The pre-scan MUST see all of them. It once read `world.list` alone, so every
/// class living in another list (all of `cocoaui.list` — `CocoaUI`,
/// `CocoaBrowser`, `CocoaToolbarAction`, …) looked brand-new and got dumped
/// wholesale into the additions file. That file is appended to `world.list`,
/// which loads BEFORE `cocoaui.list`, so the duplicate definition then lost a
/// shape race against the real one and the boot died with "cannot change shape
/// of existing class CocoaToolbarAction". Observed live 2026-07-20.
fn read_all_lists(world_dir: &Path) -> Result<Vec<String>, String> {
    let mut names: Vec<String> = Vec::new();
    let dir =
        fs::read_dir(world_dir).map_err(|e| format!("reading {}: {e}", world_dir.display()))?;
    let mut lists: Vec<PathBuf> = dir
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().is_some_and(|x| x == "list"))
        .collect();
    lists.sort(); // deterministic order
    for list in lists {
        let text = fs::read_to_string(&list).unwrap_or_default();
        for n in parse_list(&text) {
            if !names.contains(&n) {
                names.push(n);
            }
        }
    }
    Ok(names)
}

/// Ensure the additions file is named in `world.list` (appended last, so its
/// reopenings see every earlier class) — otherwise the classes/methods the
/// exporter just wrote there would never re-import.
fn ensure_in_world_list(world_dir: &Path, entries: &[String]) -> Result<(), String> {
    if entries.iter().any(|e| e == ADDITIONS_FILE) {
        return Ok(());
    }
    let list_path = world_dir.join("world.list");
    let mut text = fs::read_to_string(&list_path).unwrap_or_default();
    if !text.ends_with('\n') {
        text.push('\n');
    }
    text.push_str(&format!(
        "\n# GUI-created classes/methods, collected by 'Save World to Files'.\n{ADDITIONS_FILE}\n"
    ));
    fs::write(&list_path, text).map_err(|e| format!("updating world.list: {e}"))
}

/// Write the image's current state over `world_dir`'s `.mst` files in place.
pub fn export_world_dir(image: &Image, world_dir: &Path) -> Result<ExportStats, String> {
    // `entries` = world.list only (it alone decides where the additions file is
    // registered), but the PRE-SCAN below must see every list's files — see
    // `read_all_lists` for the boot-breaking bug that scanning world.list alone
    // caused.
    let entries = read_world_list(world_dir)?;
    let all_entries = read_all_lists(world_dir)?;
    // The hand-authored files (every list, minus the exporter-owned additions
    // file, which pass 2 regenerates wholesale). Non-existent names are skipped
    // so a list naming a not-yet-written file can't abort the export.
    let files: Vec<PathBuf> = all_entries
        .iter()
        .filter(|n| n.as_str() != ADDITIONS_FILE)
        .map(|n| world_dir.join(n))
        .filter(|p| p.exists())
        .collect();

    // Pre-scan: `present` = every (class, side, selector) that lives in some
    // hand-authored file (anything NOT here is "new" → the additions file).
    // `last_occ` = the index of the LAST file (in load order) that defines each
    // method: a method reopened/overridden across files (e.g. TranscriptStream
    // >>show: is basic in 04_transcript, printString-aware in 19_printing) has
    // several occurrences, but the image holds only the effective (latest) one,
    // so only its LAST file may carry it — splicing the latest into an earlier
    // occurrence would wrongly overwrite an intentional override.
    let mut present: HashSet<(String, String, String)> = HashSet::new();
    let mut last_occ: HashMap<(String, String, String), usize> = HashMap::new();
    for (idx, f) in files.iter().enumerate() {
        let text = fs::read_to_string(f).map_err(|e| format!("reading {}: {e}", f.display()))?;
        for c in mst::parse_mst_source(&text) {
            for m in &c.methods {
                let side = if m.is_class_side { "class" } else { "instance" };
                let key = (c.name.clone(), side.to_string(), m.selector.clone());
                present.insert(key.clone());
                last_occ.insert(key, idx); // later file wins → last occurrence
            }
        }
    }

    let mut stats = ExportStats::default();

    // ── Pass 1: reconcile each file's methods with the image ──
    //   Live + changed → splice the new body (only into the LAST file that
    //                    defines it; earlier overrides stay exactly as written);
    //   Deleted (tombstone) → remove the method from the file (every occurrence);
    //   Absent (unknown to the image) → leave untouched — never delete blindly.
    for (idx, f) in files.iter().enumerate() {
        let text = fs::read_to_string(f).map_err(|e| format!("reading {}: {e}", f.display()))?;
        let mut new_text = text.clone();
        for c in mst::parse_mst_source(&text) {
            for m in &c.methods {
                let side_str = if m.is_class_side { "class" } else { "instance" };
                let key = (c.name.clone(), side_str.to_string(), m.selector.clone());
                let side = if m.is_class_side {
                    crate::Side::Class
                } else {
                    crate::Side::Instance
                };
                match image
                    .method_presence(&c.name, side, &m.selector)
                    .map_err(|e| format!("querying {}>>{}: {e}", c.name, m.selector))?
                {
                    crate::MethodPresence::Live(db_src) => {
                        if last_occ.get(&key) == Some(&idx) && db_src != m.source {
                            // The parsed source is a verbatim, unique substring of
                            // the file, so a single find/replace is exact.
                            if let Some(pos) = new_text.find(&m.source) {
                                new_text.replace_range(pos..pos + m.source.len(), &db_src);
                                stats.methods_updated += 1;
                            }
                        }
                    }
                    crate::MethodPresence::Deleted => {
                        if let Some(removed) = remove_block(&new_text, &m.source) {
                            new_text = removed;
                            stats.methods_removed += 1;
                        }
                    }
                    crate::MethodPresence::Absent => {}
                }
            }
        }
        if new_text != text {
            fs::write(f, &new_text).map_err(|e| format!("writing {}: {e}", f.display()))?;
            stats.files_changed += 1;
        }
    }

    // ── Pass 2: place homeless methods (created in the image, not yet in any
    // file) into their class's home file where one is known — appended there as
    // a reopening block, next to the class's other methods — else into the
    // catch-all additions file (with the full definition for a brand-new class).
    let mut additions = String::new();
    let mut home_appends: HashMap<String, String> = HashMap::new();
    for c in image
        .all_classes()
        .map_err(|e| format!("listing classes: {e}"))?
    {
        // `all_methods_of` returns only live (non-deleted) methods.
        let homeless: Vec<String> = image
            .all_methods_of(&c.name)
            .map_err(|e| format!("listing {}'s methods: {e}", c.name))?
            .into_iter()
            .filter(|m| {
                !present.contains(&(
                    c.name.clone(),
                    m.side.as_str().to_string(),
                    m.selector.clone(),
                ))
            })
            .map(|m| m.source)
            .collect();
        if homeless.is_empty() {
            continue;
        }
        let is_new_class = !present.iter().any(|(cls, _, _)| cls == &c.name);
        let superclass = c.superclass.as_deref().unwrap_or("Object");
        let home = if is_new_class {
            None
        } else {
            image
                .class_home_file(&c.name)
                .map_err(|e| format!("home of {}: {e}", c.name))?
        };
        match home {
            Some(hf) if hf != ADDITIONS_FILE && entries.iter().any(|e| e == &hf) => {
                let block = class_block(superclass, &c.name, "", "", &homeless, false);
                home_appends
                    .entry(hf)
                    .or_default()
                    .push_str(&format!("\n{block}"));
                stats.methods_added += homeless.len();
            }
            _ => {
                additions.push_str(&class_block(
                    superclass,
                    &c.name,
                    &c.instance_vars,
                    &c.class_vars,
                    &homeless,
                    is_new_class,
                ));
                additions.push('\n');
                if is_new_class {
                    stats.classes_added += 1;
                }
                stats.methods_added += homeless.len();
            }
        }
    }

    // Append the home-file reopening blocks.
    for (fname, appended) in home_appends {
        let path = world_dir.join(&fname);
        let mut text =
            fs::read_to_string(&path).map_err(|e| format!("reading {}: {e}", path.display()))?;
        if !text.ends_with('\n') {
            text.push('\n');
        }
        text.push_str(&appended);
        fs::write(&path, &text).map_err(|e| format!("writing {}: {e}", path.display()))?;
        stats.files_changed += 1;
    }

    // The additions file (brand-new classes + methods with no home).
    let additions_path = world_dir.join(ADDITIONS_FILE);
    let existing = fs::read_to_string(&additions_path).unwrap_or_default();
    if additions.is_empty() {
        if additions_path.exists() && !existing.is_empty() {
            fs::write(&additions_path, "")
                .map_err(|e| format!("clearing {}: {e}", additions_path.display()))?;
            stats.files_changed += 1;
        }
    } else {
        let content = format!("{ADDITIONS_HEADER}\n{additions}");
        if existing != content {
            fs::write(&additions_path, &content)
                .map_err(|e| format!("writing {}: {e}", additions_path.display()))?;
            stats.files_changed += 1;
        }
        ensure_in_world_list(world_dir, &entries)?;
    }

    Ok(stats)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{Image, Side};

    /// The pre-scan must span EVERY `*.list`, not just `world.list`. It used to
    /// read `world.list` alone, so a class defined in a sibling list looked
    /// brand-new and got dumped whole into the additions file — which is
    /// registered in `world.list` and therefore loads BEFORE the sibling list,
    /// so the duplicate definition then lost a shape race against the real one
    /// and the boot died ("cannot change shape of existing class …"). Observed
    /// live 2026-07-20 with `CocoaToolbarAction`.
    #[test]
    fn export_scans_every_list_so_sibling_list_classes_are_not_duplicated() {
        let dir = std::env::temp_dir().join(format!("macvm_export_lists_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        // Core class in world.list; UI class in a SEPARATE list (the cocoaui.list
        // arrangement the real world uses).
        fs::write(
            dir.join("10_foo.mst"),
            "Object subclass: Foo [\n    | x |\n    bump [\n        x := 1\n    ]\n]\n",
        )
        .unwrap();
        fs::write(
            dir.join("60_ui.mst"),
            "Object subclass: Ui [\n    | b |\n    act [\n        ^b\n    ]\n]\n",
        )
        .unwrap();
        fs::write(dir.join("world.list"), "10_foo.mst\n").unwrap();
        fs::write(dir.join("ui.list"), "60_ui.mst\n").unwrap();

        let image = Image::open(&dir.join("image.sqlite3")).unwrap();
        crate::import::import_world_dir(&image, &dir).unwrap();
        crate::import::import_list_file(&image, &dir, "ui.list").unwrap();

        // A fresh export must be a pure no-op: `Ui` already lives in ui.list, so
        // nothing may be re-emitted for it.
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(
            s,
            ExportStats::default(),
            "fresh export must touch nothing, got {s:?}"
        );

        let adds_path = dir.join(ADDITIONS_FILE);
        let adds = fs::read_to_string(&adds_path).unwrap_or_default();
        assert!(
            !adds.contains("subclass: Ui"),
            "a class from a sibling list must NOT be duplicated into the additions file: {adds}"
        );
        assert!(
            !fs::read_to_string(dir.join("world.list"))
                .unwrap()
                .contains(ADDITIONS_FILE),
            "no additions file to register, so world.list must be left alone"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn export_is_idempotent_splices_edits_and_homes_new_methods() {
        let dir = std::env::temp_dir().join(format!("macvm_export_{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        // A tiny hand-authored world file.
        let foo = "\"a comment\"\nObject subclass: Foo [\n    | x |\n    bump [\n        x := x + 1\n    ]\n    x [\n        ^x\n    ]\n]\n";
        fs::write(dir.join("10_foo.mst"), foo).unwrap();
        fs::write(dir.join("world.list"), "10_foo.mst\n").unwrap();

        let image = Image::open(&dir.join("image.sqlite3")).unwrap();
        crate::import::import_world_dir(&image, &dir).unwrap();

        // 1) Idempotent: image matches files → export is a no-op, byte-for-byte.
        assert_eq!(
            export_world_dir(&image, &dir).unwrap(),
            ExportStats::default(),
            "a fresh export must touch nothing"
        );
        assert_eq!(
            fs::read_to_string(dir.join("10_foo.mst")).unwrap(),
            foo,
            "unchanged file stays byte-identical"
        );

        // 2) Edit a method in the image → spliced into the owning file, alone.
        image
            .set_method_source(
                "Foo",
                Side::Instance,
                "x",
                "x [\n        ^x ifNil: [ 0 ]\n    ]",
            )
            .unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(
            (s.files_changed, s.methods_updated),
            (1, 1),
            "exactly one edit spliced, got {s:?}"
        );
        let after = fs::read_to_string(dir.join("10_foo.mst")).unwrap();
        assert!(
            after.contains("ifNil: [ 0 ]"),
            "edited body present: {after}"
        );
        assert!(
            after.contains("bump ["),
            "untouched method preserved: {after}"
        );
        // Idempotent again after the edit.
        assert_eq!(
            export_world_dir(&image, &dir).unwrap(),
            ExportStats::default()
        );

        // 3) New method on an EXISTING class → appended to that class's home
        // file (next to its siblings), not the catch-all additions file.
        image
            .create_or_reopen_method(
                "Foo",
                Side::Instance,
                "reset",
                "",
                "reset [\n        x := 0\n    ]",
            )
            .unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(s.methods_added, 1, "one new method, got {s:?}");
        let foo_txt = fs::read_to_string(dir.join("10_foo.mst")).unwrap();
        assert!(
            foo_txt.contains("reset ["),
            "new method appended to home file: {foo_txt}"
        );
        assert!(
            !dir.join(ADDITIONS_FILE).exists()
                || fs::read_to_string(dir.join(ADDITIONS_FILE))
                    .unwrap()
                    .is_empty(),
            "a homed method must not spill into the additions file"
        );
        assert_eq!(
            export_world_dir(&image, &dir).unwrap(),
            ExportStats::default()
        );

        // 4) Delete a method in the image → removed from its file, siblings kept.
        image.remove_method("Foo", Side::Instance, "bump").unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!(s.methods_removed, 1, "one deletion exported, got {s:?}");
        let foo_txt = fs::read_to_string(dir.join("10_foo.mst")).unwrap();
        assert!(
            !foo_txt.contains("bump ["),
            "deleted method gone: {foo_txt}"
        );
        assert!(foo_txt.contains("x ["), "other methods kept: {foo_txt}");

        // 5) A brand-new class → the additions file, with its full definition.
        let lo = image.next_load_order().unwrap();
        image
            .add_class("Gadget", Some("Object"), "", "", "", "", lo)
            .unwrap();
        image
            .create_or_reopen_method("Gadget", Side::Instance, "go", "", "go [ ^42 ]")
            .unwrap();
        let s = export_world_dir(&image, &dir).unwrap();
        assert_eq!((s.classes_added, s.methods_added), (1, 1), "{s:?}");
        let adds = fs::read_to_string(dir.join(ADDITIONS_FILE)).unwrap();
        assert!(
            adds.contains("Object subclass: Gadget ["),
            "new class in additions: {adds}"
        );

        // 6) Round-trip: re-import the exported tree.
        let image2 = Image::open(&dir.join("image2.sqlite3")).unwrap();
        crate::import::import_world_dir(&image2, &dir).unwrap();
        assert!(
            image2
                .method_source("Foo", Side::Instance, "reset")
                .unwrap()
                .is_some(),
            "added method round-trips"
        );
        assert!(
            image2
                .method_source("Foo", Side::Instance, "bump")
                .unwrap()
                .is_none(),
            "deleted method stays gone"
        );
        assert!(
            image2.class_exists("Gadget").unwrap(),
            "new class round-trips"
        );

        let _ = fs::remove_dir_all(&dir);
    }
}
