"""Turn `docs/winui-cookbook.md`'s smalltalk blocks into a driver script.

Every fenced ```smalltalk block becomes one `gui doit`, wrapped in a handler
that records the failure and CONTINUES. That wrapping is the whole design: an
unhandled error in example three would abort the run and say nothing about
examples four onward, so one broken snippet would hide four others and the gate
would have to be fixed once per snippet.

Wrapping is textual and therefore has one requirement of the prose: a block must
be a sequence of statements, since it is pasted inside `[ ... ]`. That is what a
Workspace doit is anyway, so the constraint costs the documentation nothing —
and it is why the examples read as things you would actually type rather than as
things arranged to be testable.

Deliberately NOT a Markdown parser. A regex over fences is enough for a file
this shape, and a dependency would make `just gate-cookbook` need a pip install
to tell you whether your docs are true.
"""

import io
import re
import sys

md, out = sys.argv[1], sys.argv[2]
src = io.open(md, encoding="utf-8", newline="").read()

blocks = re.findall(r"```smalltalk\r?\n(.*?)```", src, re.S)
if not blocks:
    sys.exit("no ```smalltalk blocks in " + md)

lines = [
    "# GENERATED by scripts/cookbook-to-tcl.py from docs/winui-cookbook.md.",
    "# Do not edit — edit the cookbook. Every block below is a doit against a",
    "# live window, so a snippet that stopped working turns this gate red.",
    "gui connect 7717",
    "gui drain now",
    "gui doit {WinShell resetExampleFailures}",
    "gui doit {WinShell switchToView: #canvas}",
    "gui drain now",
]

for i, body in enumerate(blocks, 1):
    body = body.replace("\r\n", "\n").strip()
    # Tcl braces nest, so a snippet containing an unbalanced { or } would end
    # the argument early and produce a syntax error a long way from the cause.
    # Smalltalk uses [ ] for blocks and { } only for brace arrays, so this is
    # rare — but silently generating a broken driver is worse than saying so.
    if body.count("{") != body.count("}"):
        sys.exit("cookbook block %d has unbalanced braces; tcl cannot carry it" % i)
    lines.append("gui doit {[")
    lines.append(body)
    lines.append("] on: Error do: [ :e | WinShell noteExampleFailure:")
    lines.append("    'block %d — ' , e messageText ]}" % i)

lines += [
    'puts "COOK blocks %d"' % len(blocks),
    'puts "COOK failures [gui eval {WinShell exampleFailureCount}]"',
    'puts "COOK report [gui eval {WinShell exampleFailureReport}]"',
    "puts \"COOK snap [gui snap C:/projects/WINARM/target/winui-cookbook.png]\"",
    "gui quit",
    "",
]

io.open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
print("%d blocks -> %s" % (len(blocks), out))
